### ISSUE TITLE
Make this part of `gen-mapping`?

### ISSUE THREAD

**Issue by benmccann** [jridgewell/set-array#2]
This package is only used by `gen-mapping` and so I wonder if it might make sense to just make the code part of that package. It would reduce the number of packages that need to be resolved by package mangers and Node.js, reduce bandwidth and space in `node_modules` (e.g. only one readme, package.json, and license file would be distributed instead of two), make maintenance easier, and make is so that you never have to worry about breaking changes to the code here.

**Comment by jridgewell** [comment]
That would make sense. It was originally used by both `gen-mapping` and [remapping](https://github.com/ampproject/remapping), but then I rewrote `remapping` to just use `gen-mapping` directly.

Would you wanna make the PR? Note, I'm in the middle of migrating to a monorepo at https://github.com/jridgewell/sourcemaps, so the correct repo is there and not `github.com:jridgewell/gen-mapping`
